### ISSUE TITLE
Composer deprecation notice (Class X does not comply with psr-0 autoloading standard)

### ISSUE THREAD

**Issue by prudloff-insite** [easyrdf/easyrdf#318]
Since 1.10 (https://github.com/composer/composer/pull/8397), Composer displays a deprecation notice when installing easyrdf/easyrdf 0.9.1:
```
Deprecation Notice: Class EasyRdf_Parser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Parser/JsonLdImplementation.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /home/pierre/.config/composer/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class EasyRdf_Serialiser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Serialiser/JsonLd_real.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /home/pierre/.config/composer/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

**Comment by neclimdul** [comment]
Noticed this as well. Looking through the project code, this doesn't seem to exist in master getting a 0.10 release would fix this. Getting releases seems to be pretty hard though #299

**Comment by k00ni** [comment]
Hi @prudloff-insite and @neclimdul, i forked EasyRdf to allow further maintenance and development:

https://github.com/sweetyrdf/easyrdf

[First release](https://github.com/sweetyrdf/easyrdf/issues/2) is on the way and contains EasyRdf's latest changes (master branch) and a few additional fixes. Maybe you are interested.

**Comment by njh** [comment]
This will be fixed when I release version 1.0.0. 

Note that this will be a breaking change and you will to replace `EasyRdf_Graph` with `\EasyRdf\Graph` everywhere in your code.

**Comment by njh** [comment]
Packagist was refusing to update from the easyrdf repo because it didn't like `PHPUnit/PHPUnit` being in capitals in the [0.9.x](https://github.com/easyrdf/easyrdf/tree/0.9.x) branch.

I have just fixed the composer.json in that branch and it is happy again now.

**Comment by k00ni** [comment]
Is this solved?

**Comment by njh** [comment]
Pretty sure this is fixed now that version 1.0.0 is released.

Let me know if you are still having problems.

**Comment by ChristopherMatthews** [comment]
I'm running Composer 2.0.4 and still receive the following warnings:

`Class EasyRdf_Serialiser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Serialiser/JsonLd_real.php does not comply with psr-0 autoloading standard. Skipping.`

`Class EasyRdf_Parser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Parser/JsonLdImplementation.php does not comply with psr-0 autoloading standard. Skipping.`

**Comment by k00ni** [comment]
I was not able to find the files you posted, e.g. `lib/EasyRdf/Serialiser/JsonLd_real.php`. Current content of folder `Serialiser` can be seen here: https://github.com/easyrdf/easyrdf/tree/master/lib/Serialiser

Can you paste your `composer.json` please?

**Comment by ChristopherMatthews** [comment]
```
{
    "name": "pantheon-systems/example-drops-8-composer",
    "description": "Install drops-8 with Composer on Pantheon.",
    "type": "project",
    "license": "MIT",
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "php": ">=7.3",
        "composer/installers": "^1.9",
        "cweagans/composer-patches": "^1.7",
        "drupal/address": "~1.8",
        "drupal/admin_toolbar": "~2.0",
        "drupal/block_class": "~1.0",
        "drupal/bootstrap": "~3.20",
        "drupal/core-composer-scaffold": "^8.9",
        "drupal/core-recommended": "^8.9",
        "drupal/ctools": "~3.2",
        "drupal/dynamic_entity_reference": "~1.7",
        "drupal/entity_browser": "~2.2",
        "drupal/entity_reference_display": "~1.3",
        "drupal/extlink": "~1.3",
        "drupal/field_formatter_class": "~1.1",
        "drupal/field_group": "~3.0",
        "drupal/file_replace": "~1.2",
        "drupal/geolocation": "~3.0",
        "drupal/glazed_helper": "~1.5",
        "drupal/google_analytics": "~3.1",
        "drupal/honeypot": "~2.0",
        "drupal/imagemagick": "~3.1",
        "drupal/login_redirect_per_role": "~1.6",
        "drupal/mailsystem": "~4.2",
        "drupal/menu_block": "~1.5",
        "drupal/metatag": "~1.10",
        "drupal/multiple_registration": "~2.87",
        "drupal/pantheon_advanced_page_cache": "~1.0",
        "drupal/pathauto": "~1.4",
        "drupal/profile": "~1.1",
        "drupal/protected_pages": "~1.1",
        "drupal/redirect": "~1.4",
        "drupal/simple_sitemap": "~3.3",
        "drupal/smart_trim": "~1.1",
        "drupal/soembed": "~2.0",
        "drupal/swiftmailer": "~2.0",
        "drupal/token": "~1.5",
        "drupal/upgrade_status": "~2.5",
        "drupal/views_bootstrap": "~4.1",
        "drupal/views_bulk_operations": "~3.6",
        "drupal/webform": "~5.4",
        "drush/drush": "^8.4.5",
        "pantheon-systems/drupal-integrations": "^8",
        "zaporylie/composer-drupal-optimizations": "^1.0"
    },
    "require-dev": {
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "autoload": {
        "classmap": [
            "scripts/composer/ScriptHandler.php"
        ]
    },
    "scripts": {
        "build-assets": [
            "@prepare-for-pantheon",
            "composer install --optimize-autoloader --no-dev"
        ],
        "prepare-for-pantheon": "DrupalProject\\composer\\ScriptHandler::prepareForPantheon",
        "post-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-create-project-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ]
    },
    "extra": {
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/libraries/{$name}": ["type:drupal-library"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/Commands/contrib/{$name}": ["type:drupal-drush"],
            "web/private/scripts/quicksilver/{$name}/": ["type:quicksilver-script"]
        },
        "build-env": {
            "install-cms": [
                "drush site-install standard --account-mail={account-mail} --account-name={account-name} --account-pass={account-pass} --site-mail={site-mail} --site-name={site-name} --yes"
            ],
            "export-configuration": "drush config-export --yes"
        },
        "drupal-scaffold": {
            "allowed-packages": [
                "pantheon-systems/drupal-integrations"
            ],
            "locations": {
                "web-root": "./web"
            },
            "file-mapping": {
                "[project-root]/.editorconfig": false
            }
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "platform": {
            "php": "7.3"
        }
    }
}
```

**Comment by k00ni** [comment]
I used a reduced version of your `composer.json` because I ran into memory shortages frequently:

```json
{
    "name": "pantheon-systems/example-drops-8-composer",
    "description": "Install drops-8 with Composer on Pantheon.",
    "type": "project",
    "license": "MIT",
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "php": ">=7.3",
        "composer/installers": "^1.9",
        "cweagans/composer-patches": "^1.7",
        "drupal/address": "~1.8",
        "drupal/admin_toolbar": "~2.0",
        "drupal/block_class": "~1.0",
        "drupal/bootstrap": "~3.20",
        "drupal/core-composer-scaffold": "^8.9",
        "drupal/core-recommended": "^8.9",
        "drupal/ctools": "~3.2",
        "drupal/dynamic_entity_reference": "~1.7",
        "drupal/entity_browser": "~2.2",
        "drupal/entity_reference_display": "~1.3",
        "drupal/extlink": "~1.3",
        "drupal/field_formatter_class": "~1.1",
        "drupal/field_group": "~3.0",
        "drupal/file_replace": "~1.2",
        "drupal/geolocation": "~3.0",
        "drupal/glazed_helper": "~1.5",
        "drupal/google_analytics": "~3.1",
        "drupal/honeypot": "~2.0",
        "drupal/imagemagick": "~3.1",
        "drupal/login_redirect_per_role": "~1.6",
        "drupal/mailsystem": "~4.2",
        "drupal/menu_block": "~1.5",
        "drupal/metatag": "~1.10"
    },
    "minimum-stability": "alpha",
    "prefer-stable": true
}
```

Afterwards I checked what EasyRdf was installed:

```
composer why easyrdf/easyrdf
drupal/core              8.9.7  requires  easyrdf/easyrdf (^0.9)   
drupal/core-recommended  8.9.7  requires  easyrdf/easyrdf (0.9.1)
```

Did I missed something? If not, it seems that EasyRdf `0.9.1` is still in use (required by drupal/core-recommended  8.9.7). That could explain, why composer complains about faulty PSR-0 usage.

**Comment by k00ni** [comment]
Please reopen, if this is still not fixed.
